
<!-- END OF CONTENT -->

        <footer class="site-footer">
            <div class="container">

                <div class="row row--spacing-fixed row--margin-medium row--margin-medium-xs row--separated">
                    <div class="row__item">

                        <a class="site-footer__logo" href="<?php echo url('index') ?>">
                            <?php echo __("Eppelduerfer Jugend") ?>
                        </a>

                    </div>
                    <div class="row__item" style="flex-grow: 0.5;">

                        <nav class="footer-nav">
                            <ul class="footer-nav__list">
                                <li class="footer-nav__item">
                                    <a href="<?php echo url('index') ?>" class="footer-nav__link">
                                        <?php echo __("Iwwer eis") ?>
                                    </a>
                                </li>
                                <li class="footer-nav__item">
                                    <a href="<?php echo url('activities') ?>" class="footer-nav__link">
                                        <?php echo __("Aktivitéiten") ?>
                                    </a>
                                </li>
                                <li class="footer-nav__item">
                                    <a href="<?php echo url('spaghettisfest') ?>" class="footer-nav__link">
                                        <?php echo __("Spaghettisfest") ?>
                                    </a>
                                </li>
                                <li class="footer-nav__item">
                                    <a class="footer-nav__link" href="<?php echo url('eppeldorf') ?>">
                                        <?php echo __("Eppelduerf") ?>
                                    </a>
                                </li>
                                <li class="footer-nav__item">
                                    <a href="<?php echo url('contact') ?>" class="footer-nav__link">
                                        <?php echo __("Kontakt") ?>
                                    </a>
                                </li>
                                <li class="footer-nav__item">
                                    <a href="https://www.facebook.com/eppelduerferjugend/" class="footer-nav__link" target="_blank">
                                        <?php echo __("Facebook") ?>
                                    </a>
                                </li>
                            </ul>
                        </nav>

                    </div>
                    <div class="row__item" style="flex-grow: 1.5;">

                        <p><?php echo __("E Veräi vu jonke Leit aus ganz Lëtzebuerg, déi sech regelméisseg treffen, Events organiséieren a sech fir eng Gemeinschaft zu Eppelduerf asetzen.") ?></p>

                        <p><?php echo __("Mat frëndlecher Ënnerstëtzung vun der %s", '<a href="http://www.aerenzdall.lu/" target="_blank">' . __("Aerenzdallgemeng") . '</a>') ?> <span class="icon icon--heart"></span></p>

                        <p><?php echo __("Entwéckelt vum %s an ënnert der MIT Lizenz op %s verfügbar.", '<a href="https://fraenz.frieder.es/" target="_blank">Fränz Friederes</a>', '<a href="https://github.com/ffraenz/EppelduerferJugendLu" target="_blank">GitHub</a>') ?></p>

                    </div>
                    <div class="row__item">

                        <dl>
                            <dt class="site-footer__label"><?php echo __("IBAN & BIC") ?></dt>
                            <dd class="site-footer__value">LU13 0019 4655 5279 4000<br>BCEELULL</dd>
                            <dt class="site-footer__label"><?php echo __("Siège sociale") ?></dt>
                            <dd class="site-footer__value">Rullewee, 5<br>L-9365 Eppelduerf</dd>
                            <dt class="site-footer__label"><?php echo __("No RCSL") ?></dt>
                            <dd class="site-footer__value">F0010506</dd>
                        </dl>

                    </div>
                </div>

            </div>
        </footer>

        <script src="/js/jquery.min.js"></script>
        <script src="/js/script.min.js"></script>

    </body>
</html>
