<?php

setTitle('Eppelduerfer Jugend');

?>
<!DOCTYPE html>
<html lang="<?php echo str_replace('_', '-', getData('locale')) ?>">
    <head>
        <meta charset="UTF-8">

        <title><?php echo escapeHtml(getTitle(true)) ?></title>

        <link rel="stylesheet" href="/css/style.min.css">
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?v1">

        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

        <meta property="og:site_name" content="Eppelduerfer Jugend">
        <meta property="og:title" content="<?php echo escapeAttr(getData('open_graph_title') !== null ? getData('open_graph_title') : getTitle()) ?>">
        <meta property="og:description" content="<?php echo escapeAttr(getData('description')) ?>">
        <meta property="og:url" content="<?php echo escapeAttr(getData('page_url')) ?>">
        <meta property="og:type" content="website">
        <meta property="fb:app_id" content="<?php echo getConfig('facebook_app_id') ?>">
        <?php if ($openGraphImage = getData('open_graph_image')) { ?>

        <meta property="og:image" content="<?php echo $openGraphImage ?>">
        <meta property="og:image:width" content="1200">
        <meta property="og:image:height" content="630">
        <meta name="twitter:card" content="summary_large_image">
        <?php } ?>
        <?php if ($structuredData = getData('structured_data')) { ?>

        <script type="application/ld+json">
        <?php echo indent(json_encode($structuredData, JSON_PRETTY_PRINT), 2) ?>

        </script>
        <?php } ?>

        <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-80244249-1', 'auto');
        ga('send', 'pageview');
        </script>

    </head>
    <body>

<!-- BEGIN OF CONTENT -->
