
<section class="section section--spaghettisfest">
    <div class="container">

        <div class="row row--spacing-fixed row--margin-medium">
            <div class="row__item">

                <h3 class="section__heading" data-reveal="fade-in-right 0.1">
                    <span class="cal-sheet cal-sheet--red cal-sheet--strong">
                        <span class="cal-sheet__day">15</span>
                        <span class="cal-sheet__month">Aug</span>
                    </span>
                    <?php echo __("Spaghettisfest") ?>
                </h3>

                <p data-reveal="fade-in-right 0.15s"><?php echo __("Säit iwwer 30 Joer versammelen sech op Maria Himmelfahrt, dem 15. August hongereg Leit zu Eppelduerf. Op dësem Dag gi mëttes an owes grouss Portioune Spaghetti gekacht an d’Zesummekomme bis an d’Nuecht era gefeiert.") ?></p>

                <div class="section__actions">
                    <ul class="row">
                        <li class="row__item">
                            <a class="btn btn--red-on-gray" href="<?php echo url('spaghettisfest') ?>" data-reveal="btn-fade-in-top 0.6s">
                                <?php echo __("Weider Informatiounen") ?>
                            </a>
                        </li>
                    </ul>
                </div>

            </div>
            <div class="row__item">

                <div style="min-height: 200px;">
                    <img src="/assets/logo-spaghettisfest.svg" style="position: absolute; top: 0; left: 0; width: 100%;" alt="Spaghettisfest">
                </div>

            </div>
        </div>

    </div>
</section>
