
<section class="section section--align-center section--image">
    <div class="image-cover image-cover--overlay-green">
        <img class="image-cover__image" src="/assets/photos/1964-03-07-eppeldorfer-dorfjugend.jpg" alt="Eppeldorfer Dorfjugend – Revue, 7. Mäerz 1964">
        <div class="image-cover__source">
            <div class="tooltip tooltip--white tooltip--left image-cover__source-tooltip">
                Eppeldorfer Dorfjugend – Revue, 7. Mäerz 1964
            </div>
        </div>
    </div>
    <div class="container">

        <h3 class="section__heading"><?php echo __("Du bass interesséiert bäi eis Member ze ginn?") ?></h3>

        <p><?php echo __("Du hues Loscht dech z'engagéieren, un der Organisatioun vun Events ze wuessen an dobäi nei Leit kennenzeléieren? Wou s du wunns, deng Nationalitéit, däi Geschlecht ewéi deng sexuell Orientéierung spille bäi eis keng Roll. Sierf eis Wëllkomm!") ?></p>

        <div class="section__actions">
            <ul class="row row--align-center">
                <li class="row__item">
                    <a class="btn btn--ghost-white" href="<?php echo url('contact') ?>">
                        <span class="icon icon--message"></span>
                        <?php echo __("Schreif eis") ?>
                    </a>
                </li>
                <li class="row__item">
                    <a class="btn btn--ghost-white" href="/documents/formular-baeitrett.pdf" target="_blank">
                        <span class="icon icon--document"></span>
                        <?php echo __("Bäitrëtt Formular") ?>
                    </a>
                </li>
            </ul>
        </div>

    </div>
</section>
